Changed logic for LAST_TAG. Getting only tags for particular git branch + added tag validation regex

diff --git a/actions.yml b/actions.yml
--- a/actions.yml
+++ b/actions.yml
@@ -17,9 +17,15 @@ runs:
       run: |
       CURRENT_COMMIT = $(git rev-parse HEAD)
       COMMIT_TAG = $(git tag --points-at "$CURRENT_COMMIT")
-      LAST_TAG = $(git tag -l | sort -rV | head -n 1)
+      LAST_TAG = $(git tag --merge | grep "${GITHUB_REF##*/}" | sort -rV | head -n 1)
 
-      if [ "$COMMIT_TAG" == "$LAST_TAG" ];
+      TAG_REGEX='^v?[0-9]+\.[0-9]+\.[0-9]+$'
+      if ! [[ $LAST_TAG =~ $TAG_REGEX ]];
+      then
+        echo "error: Not a valid tag" >&2; exit 1
+      fi
+
+      if [[ "$COMMIT_TAG" == "$LAST_TAG" ]];
       then
         NEW_TAG = "$COMMIT_TAG"
       else
